#!/usr/bin/env bash
#Configure a new Nginx server so that /redirect_me is redirecting to another page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https:/maykayconcept.tech/ permanent;' /etc/nginx/sites-
sudo service nginx restart
