#!/usr/bin/env bash
#Configure Nginx so that its HTTP response contains
# a custom header

sudo apt-y upgrade
sudo apt -y update
sudo apt -y install haproxy
echo "
frontend webservers
mode http
mode *.80
default_backend
web_servers

backend webservers
mode http
balance roundrobin
server 399089-web-01 52.91.153.180:80 check
server 399089-web-02 54.164.73.177:80 check
" | sudo tee /etc/haproxy/haproxy.cfg
sudo service haproxy start
