#!/usr/bin/env bash
#Configure Nginx so that its HTTP response contains
# a custom header
#
balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
    
backend webservers
    balance roundrobin
    server  399089-web-01 52.91.153.180:80 check
    server 399089-web-02 54.164.73.177:80  check
"
# Update packages
sudo apt-get -y update
sudo apt-get -y upgrade

# Add HAProxy PPA
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$balancer" | sudo tee /etc/haproxy/haproxy.cfg
sudo service nginx stop
sudo service haproxy restart
