#!/usr/bin/env bash
#This script displays the content of the file /etc/passwd.
#uername
#user id
#Home directory path for the user

while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
