#!/usr/bin/env bash
#This is a script that gives you information about the school file
#Bash script should check if the file exists and print:
#if the file exists: school file exists
#if the file does not exist: school file does not exist
#If the file exists, print:
#if the file is empty: school file is empty
#if the file is not empty: school file is not empty
#if the file is a regular file: school is a regular file
#if the file is not a regular file: (nothing)

file_path="school"

if [ -e "$file_path" ];
then
	echo "school file exists"
	if [ -s "$file_path" ];
	then
		echo "school file is not empty"
	else
		"school file is empty"
	fi
	if [ -f "$file_path" ];
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
